# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: Infrastructure/WebApi/Dockerfile
    ports:
      - 5005
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5005
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
